# Site settings
title: Zeeva's Lens
email: your-email@domain.com
url: https://example.github.io
description: "Photography and Art by Zeeva"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  85D0D4 #18bc9c #80B3FF
  secondary: 5E8C93  #2c3e50 #FD6E8A
  secondary-dark: E9C4DC #233140 #A2122F

# Footer settings
footer:
  copyright: Zeeva Chaver

# Build settings
markdown: kramdown
permalink: pretty
